### ISSUE TITLE
Rendering process fails if vendor option sortByGroup is used

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#224] opened 2021-01-24 22:50 UTC
This bug is described in detail [here](https://osgeo-org.atlassian.net/browse/GEOS-9748). I was able to load a reproduce the error using the user provided data, although I also found a much simpler way of reproducing it. Onl for reference, I will document here the steps I followed to reproduce the client problem using is data:

First I created the necessary PostGIS database:

```
$> sudo -u postgres psql postgres
psql> CREATE USER  geoserver WITH PASSWORD 'geoserver';
psql> CREATE DATABASE geoserver;
psql> GRANT ALL PRIVILEGES ON DATABASE geoserver TO geoserver;
psql> \connect geoserver
psql> CREATE EXTENSION postgis;
psql> exit;
```

Then I loaded the dump using:

```
$> sudo su - postgres
$> pg_restore --clean --no-acl --no-owner -h localhost -d geoserver -U geoserver  ./ap_lpo.dump
```

Some errors will happen during the dump load but can be safely ignored. 

Then I published the style and layer from the user in GeoServer as demoed [here](https://drive.google.com/file/d/1OxheRRnKEb-4AZss8siO5FGrbdivLinT/view?usp=sharing).

As it's commented on the issue, this error only happens when a certain number of features are used.

That say, I was able to reproduce this using the default data and layers shipped whit GeoServer, we just need to add the sorting options to the line styles:
```
<VendorOption name="sortBy">NAME</VendorOption>
<VendorOption name="sortByGroup">CFCC</VendorOption>
```

I have documented [here](https://drive.google.com/file/d/1NOVR0eYxuNh7BijiGkmbpkT3vawA2Mel/view?usp=sharing) how to reproduce it.

**Let's start by reproducing the issue, then investigate it's cause, then let's propose a plan and estimate to fix it. We  need to discuss first and agree on the estimate before moving on whit the fix implementation.**

**Comment by nmco** [comment] 2021-01-24 22:52
The sorting options are documented [here](https://docs.geoserver.org/stable/en/user/styling/sld/extensions/z-order/syntax.html).

**Comment by nmco** [comment] 2021-04-21 08:02
Let's follow the usual workflow:

1. Time-box the initial investigation of the issue to 4 hours MAXIMUM.
2. Clarify the context of the task, make sure you have everything needed to move on.
3. Provide a plan and estimate to handle the reported issue, report on the issue.
4. Wait for the green light from the PM before moving on with the implementation.

**Comment by zvrablik** [comment] 2021-04-22 07:52
* DiskMarkFeatureIterator is created to paint layer features and closed
	* it uses temp file in /tmp/ direcotry
	* when the iterator is closed, file is deleted
	* uses SimpleFeatureIO (MarkFeatureIterator line 161)
	* the iterator is used later again in ZGroupLayer drawFeatures uses ZGroupLayerPainter paintKey and could request rewind the iterator and start iterating from 0 again.
	* issue does not occur if the layer has less than 1000 features - the MemoryMarkFeatureIterator is used and the close method implementation is empty - here is the inconsistency with DiskMarkFeatureIterator

* issue in geotools - added try with resource autocloseable to geotools ZGroupLayer
	* added in commit geotools https://github.com/geotools/geotools/commit/8b5d6279474c9dc8962d279a884e508ab670ee3c

* options to solve
    * do not use try with autocloseable resource and ADD PMD mark to suppress warning and let the ZGroupLaeyrPainter close the iterator - looks like that is how it worked before
    * close the iterator, but do not delete the file and if needed again load the file and reset the iterator? - delete file on server stop or with any time delay - e.g. use the wms rendering timeout not to delete the file too soon

**Comment by nmco** [comment] 2021-04-22 10:57
Needs @nmco help to close the estimate.

**Comment by zvrablik** [comment] 2021-04-23 10:08
The iterator is closed (only if DiskMarkFeatureIterator is used), MemoryMarkFeatureIterator is fine as it does nothing when closed.
https://github.com/geotools/geotools/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java#L195-L202

The closed iterator is called again
https://github.com/geotools/geotools/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java#L118-L125

https://github.com/geotools/geotools/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayerPainter.java#L75

https://github.com/geotools/geotools/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/MarkFeatureIterator.java#L212-L215

**Comment by nmco** [comment] 2021-04-23 10:28
My recommendation @zvrablik is to:
- Don't close the iterator when creating it [HERE](https://github.com/geotools/geotools/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java#L196).
- Assuming that the close method will always be correctly invoked on [the painter object](https://github.com/geotools/geotools/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java#L130-L1352).

Can you please double check this @aaime ?

Estimate for reverting and implemented a test. A test that fails should be implemented first, if we can reproduce this whit an in-memory great, otherwise we will need an online test for PostgreSQL, but I'm not sure this is something we can easily setup, please ask @aaime.

**Comment by aaime** [comment] 2021-04-23 15:02
The painter is a closeable so that should be fine, just make sure the painter itself is closed, no matter what happens (even if the rendering goes belly up to due a OOM for example, the OOM might be transient, but if we start accumulating files that are not closed, the JVM will eventually reach some OS limit and be punished)

**Comment by zvrablik** [comment] 2021-04-23 15:07
I would like to remove the try block as we discussed on skype.

/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java#L196-L206) and add @SuppressWarnings("PMD.CloseResource") 

I am sure the iterator is closed by the ZGroupPainter which uses the iterator later.

Existing test testCrossRoadsBuildingsOnZ of ZOrderTest could be used and before running the test just set the rendering query hint Hints.MAX_MEMORY_SORT set to 2 to force use of the disk mark iterator.

Estimate 2 hours

@aaime  is this ok? Does this need backport to other maintainance branches?

**Comment by aaime** [comment] 2021-04-23 15:14
@zvrablik extend the test so that it uses both the in memory and the on disk sorting ([you can make it parametric if you want](https://www.tutorialspoint.com/junit/junit_parameterized_test.htm), or just add more test methods).

Estimate is optmimistic, you need to run full builds locally, pass QA checks as well, a PR review, and do backports to stable and maintenance (right @nmco? ). I would not go for less than 4h, 6h are probably better.

**Comment by zvrablik** [comment] 2021-04-26 06:32
> The painter is a closeable so that should be fine, just make sure the painter itself is closed, no matter what happens (even if the rendering goes belly up to due a OOM for example, the OOM might be transient, but if we start accumulating files that are not closed, the JVM will eventually reach some OS limit and be punished)

@aaime The iterators are closed without any object allocation [HERE](http://github.com/geotools/geotools/blob/9437e2c6ee3405278b74c154ca3373bb87401a29/modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java#L127-L135), Only allocation I see is in java code when deleting file and jvm uses security manager. Is this ok to ignore?

**Comment by zvrablik** [comment] 2021-04-26 06:35
updated estimates as recommended by Andrea
17 hours ( contains 11 hours already taken to setup, reproduce and investigate the issue)

**Comment by nmco** [comment] 2021-04-26 14:05
So you spend 11 hours investigating \ prepare and the estimate and you need 6 hours? In that case go ahead.

**Comment by zvrablik** [comment] 2021-04-27 12:17
I need review. Pull request is [here](https://github.com/geotools/geotools/pull/3476)

**Comment by nmco** [comment] 2021-04-30 12:12
JIRA ticket: https://osgeo-org.atlassian.net/browse/GEOT-6880

Backports done, waiting for merge.

**Closed** 2021-08-07 15:37 UTC
Labels: bug, GeoServer-GeoTools-GeoWebcache, Internal, backport-required
