### ISSUE TITLE
Error in SQL conversion when function uses a like expression

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#122] opened 2019-12-04 14:48 UTC
See [this issue](https://osgeo-org.atlassian.net/browse/GEOT-6363) which is bothering us on MapStore.

We need this to get fixed on all the available branches.

We can ask more details to @offtherailz as needed.

**Comment by imranrajjad** [comment] 2019-12-09 08:41
@simboss

### Root Cause

I have conducted initial investigation into the matter. Apparently the String function implementation  are hard wired to evaluate a feature and not a feature type. See [FilterFunction_strToLowerCase.java](https://github.com/geotools/geotools/blob/master/modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_strToLowerCase.java#L39)

Whereas the Abstract implementation of working with Like operators of gt-jdbc implementation is trying to evaluate the function through FeatureType instead of the Feature itself. Please see [FilterToSQL.]visit(PropertyIsLike filter, Object extraData)(https://github.com/geotools/geotools/blob/master/modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java#L526).  Looks to be the case with all string function related implementations. (I have no tested though).

### Proposed Fix

FilterFunction_strToLowerCase evaluation needs to be able to evaluate FeatureType and return an 
`org.opengis.feature.type.AttributeDescriptor` instance. The lower case function is not same in all databases, so will need to addressed . This will require adding a generic method inside the (https://github.com/geotools/geotools/blob/master/modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java) class, which should have generic implementation and should also allow other implementations to override it accordingly.

Estimate 3 days

**Comment by imranrajjad** [comment] 2019-12-09 12:45
PR : https://github.com/geotools/geotools/pull/2690

**Comment by simboss** [comment] 2019-12-09 13:29
thx @imranrajjad 

once this gets merged, please backport to all active branches.

**Comment by imranrajjad** [comment] 2019-12-10 12:20
backport PRs:

22.x : https://github.com/geotools/geotools/pull/2692
21.x : https://github.com/geotools/geotools/pull/2693

**Comment by nmco** [comment] 2019-12-13 09:50
Backports pull requests merged:
https://osgeo-org.atlassian.net/browse/GEOT-6363

@imranrajjad monitor GeoServer \ GeoTools for build failures.

**Closed by nmco** 2019-12-13 09:50 UTC
Labels: bug
