### ISSUE TITLE
[GEOS-9428] Authkey role service filters broken on 2.16+

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#126] opened 2019-12-12 14:48 UTC
This has been reported recently and it is captured in [this](https://osgeo-org.atlassian.net/browse/GEOS-9428) report which is pretty detailed and suggest a solution.

I am giving priority to this once since it comes from GeoNode people who are testing the new version of GeoServer.

We need to make sure whatever this was we find a way to put there a unit test to prevent this from happening int he future.

**Comment by nmco** [comment] 2019-12-13 09:56
@imranrajjad can evaluate the proposed solution (doe it makes sense? will ti actually fix the problem?), and estimate it?

**Comment by imranrajjad** [comment] 2019-12-13 15:01
@simboss 
apologies, I could not look into this today. I will get back with an estimate ASAP.

**Comment by imranrajjad** [comment] 2019-12-17 13:02
@simboss  I was unable to produce the described error on both master and 2.16.x 

My Environment:

- Win 10
- JDK 8
- Tomcat 9

I will reply on the JIRA to get more information from client

**Comment by imranrajjad** [comment] 2019-12-17 14:30
###Update 

I was able to re-produce by downloading the lastest release and related plugins and run them  into a standalone tomcat (not from IDE).  The error occurs on UI when you login to a directory which has AuthRest Role service and Geofence enabled

```
java.lang.ClassNotFoundException: net.minidev.asm.FieldFilter
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1360)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182)
	net.minidev.json.reader.JsonWriter.<clinit>(JsonWriter.java:157)
	net.minidev.json.JSONValue.<clinit>(JSONValue.java:537)
	com.jayway.jsonpath.spi.json.JsonSmartJsonProvider.<init>(JsonSmartJsonProvider.java:39)
	com.jayway.jsonpath.internal.DefaultsImpl.jsonProvider(DefaultsImpl.java:21)
	com.jayway.jsonpath.Configuration.defaultConfiguration(Configuration.java:174)
	com.jayway.jsonpath.internal.JsonContext.<init>(JsonContext.java:52)
	com.jayway.jsonpath.JsonPath.read(JsonPath.java:502)
	org.geoserver.security.GeoServerRestRoleService$1.executeWithContext(GeoServerRestRoleService.java:193)
	org.geoserver.security.GeoServerRestRoleService.connectToRESTEndpoint(GeoServerRestRoleService.java:584)
	org.geoserver.security.GeoServerRestRoleService.getRolesForUser(GeoServerRestRoleService.java:180)
	org.geoserver.security.impl.RoleCalculator.calculateRoles(RoleCalculator.java:109)
	org.geoserver.security.impl.AbstractUserGroupService.loadUserByUsername(AbstractUserGroupService.java:176)
	org.geoserver.security.concurrent.LockingUserGroupService.loadUserByUsername(LockingUserGroupService.java:259)
	org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:108)
	org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:144)
	org.geoserver.security.auth.UsernamePasswordAuthenticationProvider.authenticate(UsernamePasswordAuthenticationProvider.java:78)
	org.geoserver.security.GeoServerAuthenticationProvider.authenticate(GeoServerAuthenticationProvider.java:54)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
	org.geoserver.security.GeoServerSecurityManager$1.authenticate(GeoServerSecurityManager.java:315)
	org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	org.geoserver.security.filter.GeoServerUserNamePasswordAuthenticationFilter.doFilter(GeoServerUserNamePasswordAuthenticationFilter.java:122)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
	org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
	org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:79)
	org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:47)
	org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
	org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
```

**Comment by imranrajjad** [comment] 2019-12-17 15:07
@nmco 



`net.minidev.asm.FieldFilter` which has implementations inside one of authey`s dependencies 

The issue is being caused by the authkey dependency 

```
 <dependency>
        <groupId>com.jayway.jsonpath</groupId>
        <artifactId>json-path</artifactId>
    </dependency>    
```

The interface `net.minidev.asm.FieldFilter` is present inside on of the dependencies of json-path but it does not get packaged with authkey module and hence the class not found error. The packaging of authkey module needs to make sure that following depenency is also packaged.

```
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>accessors-smart</artifactId>
    <version>1.1</version>
</dependency>
```
Copying this dependency into the lib folder made the error go away

**Comment by nmco** [comment] 2019-12-18 08:59
So @imranrajjad is that an issue with the module assembly specification?
https://github.com/geoserver/geoserver/blob/master/src/release/ext-authkey.xml

If yes, then check @aaime comments on the GeoServer chat and then go ahead.

**Comment by imranrajjad** [comment] 2019-12-18 10:24
master : https://github.com/geoserver/geoserver/pull/3937

**Comment by nmco** [comment] 2020-01-07 15:04
Merged, thx @imranrajjad. Please backport to 2.16.x and 2.15.x, since this a fix it can \ should be backported right away.

**Comment by imranrajjad** [comment] 2020-01-08 10:44
@nmco can you please check, its not merged

**Comment by nmco** [comment] 2020-01-08 11:03
Merged.

**Comment by imranrajjad** [comment] 2020-01-08 12:21
2.16.x backport https://github.com/geoserver/geoserver/pull/3958
2.15.x backport  https://github.com/geoserver/geoserver/pull/3959

**Closed** 2020-01-30 12:25 UTC
