### ISSUE TITLE
Mixed Content issue using the WPS gs:Download 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/geoserver#216] opened 2020-11-27 12:04 UTC
While testing the gs:Download process through the new MapStore export tool I found the following issue that has been originally reported in [this](https://github.com/geosolutions-it/MapStore2/issues/6144#issuecomment-733640628) MapStore issue.

The **GetExecutionStatus** request performed by MS using HTTPs:

https://gs-stable.geo-solutions.it/geoserver/wps?service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=ebd48fbd-f8db-40ff-b11e-841fe2bbec03&authkey=42a4e18a-deb2-4f0d-9115-0d121460a256

Has the following response:

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" service="WPS" serviceInstance="http://gs-stable.geo-solutions.it/geoserver/ows?authkey=42a4e18a-deb2-4f0d-9115-0d121460a256&amp;" statusLocation="http://gs-stable.geo-solutions.it/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionStatus&amp;executionId=ebd48fbd-f8db-40ff-b11e-841fe2bbec03&amp;authkey=42a4e18a-deb2-4f0d-9115-0d121460a256" version="1.0.0">
	<wps:Process wps:processVersion="1.0.0">
		<ows:Identifier>gs:Download</ows:Identifier>
		<ows:Title>Enterprise Download Process</ows:Title>
		<ows:Abstract>Downloads Layer Stream and provides a ZIP.</ows:Abstract>
	</wps:Process>
	<wps:Status creationTime="2020-11-25T11:00:56.038Z">
		<wps:ProcessSucceeded>Process succeeded.</wps:ProcessSucceeded>
	</wps:Status>
	<wps:ProcessOutputs>
		<wps:Output>
			<ows:Identifier>result</ows:Identifier>
			<ows:Title>Zipped output files to download</ows:Title>
			<wps:Reference href="http://gs-stable.geo-solutions.it/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionResult&amp;executionId=ebd48fbd-f8db-40ff-b11e-841fe2bbec03&amp;outputId=result.zip&amp;mimetype=application%2Fzip&amp;authkey=42a4e18a-deb2-4f0d-9115-0d121460a256" mimeType="application/zip"/>
		</wps:Output>
	</wps:ProcessOutputs>
</wps:ExecuteResponse>
```

Where GeoServer put HTTP in the **wps:Reference href**. This generates the mixed content issue.

**Comment by nmco** [comment] 2020-11-27 17:30
@taba90 let's dot he usual work-flow: 
- initial investigation and estimate, max 2 hours, if we need more let's ask the client
- try to reproduce the issue, check that we have everything we need

The project and project code are:

ALMAVIVA |  C183-ALMAVIVA-2020-GeoNode-DEV
-- | --

**Comment by simboss** [comment] 2020-11-30 09:41
@taba90 keep us posted.

**Comment by taba90** [comment] 2020-11-30 09:44
@simboss  working on this

**Comment by taba90** [comment] 2020-11-30 11:59
@nmco 

- The response returned for the getExecutionStatus request is built during the Execute request.
- The only way that reported issue can occur is that the Execute request is performed with **http** and the getExectuionStatus with **https**.
- The **wps:Reference href** attribute in the response is built here and the http or https is put according to the [getScheme ](https://tomcat.apache.org/tomcat-5.5-doc/servletapi/javax/servlet/ServletRequest.html#getScheme()) method of the HttpServletRequest object. The url set in the response is built [here](https://github.com/geoserver/geoserver/blob/835bd43c1e70bd3434537d40d4452fc8e6b607fe/src/ows/src/main/java/org/geoserver/ows/util/ResponseUtils.java#L411) and set to the [RequestBaseTypeImpl](https://github.com/geotools/geotools/blob/e01e2e742e8bbe217bb316cd1698f40caac11de7/modules/ogc/net.opengis.wps/src/net/opengis/wps10/impl/RequestBaseTypeImpl.java#L302) where is later retrieve when the reponse is [built ](https://github.com/geoserver/geoserver/blob/b76bba7178d3505cd45e318e659c3b32faee4b5e/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/ExecuteResponseBuilder.java). 

- The get ExecutionStatusRequest retrieve the stored response [here](https://github.com/geoserver/geoserver/blob/6e9e25c0c7cdda9ada9f33f8255130d3afc76801/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/GetStatus.java#L45);

- If we need to avoid the exception when execute request is called over http and executionStatus is called over https the stored response needs to be updated before being returned

**Comment by nmco** [comment] 2020-11-30 12:20
@tdipisa do you know if this is the case?

> The only way that reported issue can occur is that the Execute request is performed with http and the getExectuionStatus with https.

If that's the case @tdipisa and if MapStore controls those requests, it may be enough for you to make that MapStore always use HTTPS.

That say, @taba90 it may happen that the execution and the then the get status are invoked from different URLs or even different protocols (although it's a security breach it's possible for a site to answer HTTP and HTTPS).

IMHO, the response returned for a get status should use the base URL of the get status request, not the one of the original execution, which is unfortunately now pre-computing and storing the response for the get status. I guess we could for example, make the response have a place holder for the base URL and the replace them on the file whit the base URL of the get status?

What do you suggests @taba90 ?

**Comment by tdipisa** [comment] 2020-11-30 13:24
@nmco as I reported in the issue description, MapStore is performing a request using HTTPS but in the GeoServer response we have the following:

`<wps:Reference href="http://gs-stable.geo-solutions.it/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionResult&amp;executionId=ebd48fbd-f8db-40ff-b11e-841fe2bbec03&amp;outputId=result.zip&amp;mimetype=application%2Fzip&amp;authkey=42a4e18a-deb2-4f0d-9115-0d121460a256" mimeType="application/zip"/> `

**Comment by taba90** [comment] 2020-11-30 13:34
@tdipisa  the point is about the **Execution** wps request perfomed before the **ExecutionStatusRequest** reported in the issue description. 
Are you confirm also that the Execution request in this use case is performed over **https**  as the **ExecutionStatusRequest** whom response is causing the issue? Or is it performed using **http**?

**Comment by taba90** [comment] 2020-11-30 13:42
@nmco regarding the alignment between request and stored response base url:

- [Here ](https://github.com/geoserver/geoserver/blob/6e9e25c0c7cdda9ada9f33f8255130d3afc76801/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/GetStatus.java#L51)I would add some code I would parse with a [Parser ](https://github.com/geotools/geotools/blob/2bf61f5245978f6a57e6d10009a0c084cc398b94/modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Parser.java#L68)the stored response e checked the baseUrl in the `wps:Reference href` is the same as the one in the request object store in the ExecutionStatus object. If not updates it and store Rencoding the response, returning the updated one.

**Comment by nmco** [comment] 2020-11-30 16:52
@taba90 so what's the estimate?

**Comment by taba90** [comment] 2020-11-30 16:53
estimate is **4** hours

**Comment by nmco** [comment] 2020-11-30 16:56
Summary for you @tdipisa:
- Either MapStore can make sure that we always uses HTTPS when invoking the WPS process and the get status;
- **Either we fix this behaviour in the code, the estimate is 4 hours.**

Let's know if we can move forward.

**Comment by tdipisa** [comment] 2020-11-30 17:02
@nmco @taba90 

Below are the other requests performed by MapStore under HTTPS

https://gs-stable.geo-solutions.it/geoserver/wps?service=WPS&version=1.0.0&REQUEST=Execute&authkey=fa31bc8e-c517-40c1-86fb-f109bf68ed47

POST body

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute version="1.0.0"
           	service="WPS"
           	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           	xmlns="http://www.opengis.net/wps/1.0.0"
           	xmlns:wfs="http://www.opengis.net/wfs"
           	xmlns:wps="http://www.opengis.net/wps/1.0.0"
           	xmlns:ows="http://www.opengis.net/ows/1.1"
           	xmlns:gml="http://www.opengis.net/gml"
           	xmlns:ogc="http://www.opengis.net/ogc"
           	xmlns:wcs="http://www.opengis.net/wcs/1.1.1"
           	xmlns:dwn="http://geoserver.org/wps/download"
           	xmlns:xlink="http://www.w3.org/1999/xlink"
           	xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
	<ows:Identifier>gs:DownloadEstimator</ows:Identifier>
	<wps:DataInputs>
		<wps:Input>
			<ows:Identifier>layerName</ows:Identifier>
			<wps:Data>
				<wps:LiteralData>gs:us_states</wps:LiteralData>
			</wps:Data>
		</wps:Input>
	</wps:DataInputs>
</wps:Execute>
```


https://gs-stable.geo-solutions.it/geoserver/wps?service=WPS&version=1.0.0&REQUEST=Execute&authkey=fa31bc8e-c517-40c1-86fb-f109bf68ed47

POST body

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute version="1.0.0"
           	service="WPS"
           	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           	xmlns="http://www.opengis.net/wps/1.0.0"
           	xmlns:wfs="http://www.opengis.net/wfs"
           	xmlns:wps="http://www.opengis.net/wps/1.0.0"
           	xmlns:ows="http://www.opengis.net/ows/1.1"
           	xmlns:gml="http://www.opengis.net/gml"
           	xmlns:ogc="http://www.opengis.net/ogc"
           	xmlns:wcs="http://www.opengis.net/wcs/1.1.1"
           	xmlns:dwn="http://geoserver.org/wps/download"
           	xmlns:xlink="http://www.w3.org/1999/xlink"
           	xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
	<ows:Identifier>gs:Download</ows:Identifier>
	<wps:DataInputs>
		<wps:Input>
			<ows:Identifier>layerName</ows:Identifier>
			<wps:Data>
				<wps:LiteralData>gs:us_states</wps:LiteralData>
			</wps:Data>
		</wps:Input>
		<wps:Input>
			<ows:Identifier>outputFormat</ows:Identifier>
			<wps:Data>
				<wps:LiteralData>application/zip</wps:LiteralData>
			</wps:Data>
		</wps:Input>
		<wps:Input>
			<ows:Identifier>cropToROI</ows:Identifier>
			<wps:Data>
				<wps:LiteralData>false</wps:LiteralData>
			</wps:Data>
		</wps:Input>
	</wps:DataInputs>
	<wps:ResponseForm>
		<wps:ResponseDocument storeExecuteResponse="true"
                    			status="true">
			<wps:Output asReference="true">
				<ows:Identifier>result</ows:Identifier>
			</wps:Output>
		</wps:ResponseDocument>
	</wps:ResponseForm>
</wps:Execute>
```

**Comment by nmco** [comment] 2020-11-30 17:15
So basically @tdipisa confirmed that MapStore always use HTTPS, so @taba90  we need to producer this issues (exactly this one) and put a debug point. If you need support for this @tdipisa may be able to help.

**Comment by nmco** [comment] 2020-12-01 00:11
I set up locally a GeoServer behind an HTTPS and could not reproduced this issue, I also give it a try querying gs-stable and it seems to be working as expected, GeoServer respects the configured proxy base URL:
https://drive.google.com/file/d/11yxU89eMJ79eZ5wyreCuVNDLiobvRux6/view?usp=sharing

**Comment by nmco** [comment] 2020-12-01 00:27
**Please disregard my last comment**, locally everything works fine, and remotely everything works fine, **except the ``GetExecutionStatus`` where indeed HTTP is used instead of HTTPS**.

Local:

![image](https://user-images.githubusercontent.com/1590542/100681428-9177d900-336b-11eb-8837-3a291abf2bc1.png)

Remote:

![image](https://user-images.githubusercontent.com/1590542/100681554-e7e51780-336b-11eb-85e0-c5a35bb740e6.png)

**Comment by nmco** [comment] 2020-12-01 10:21
Issue reproduced locally with the help of @randomorder and @taba90, the problem is related with the usage of HTTP proxy headers variables on the proxy base URL:

![image](https://user-images.githubusercontent.com/1590542/100728004-e55fdd80-33be-11eb-93b5-5b955b2184be.png)

Investigating deeper.

**Comment by nmco** [comment] 2020-12-01 16:23
Phew, this one was quite a roller-coast, so with the help of @aaime we were able to identify the bug and come up with a reasonable plan to fix it.

Long story short, when answering an synchronous call the WPS process will answer right away with payload providing the necessary info to retrieve the execution status, and consequently download the result. In the meantime the requested execution will start happening in a background thread.

Several things will happen here, one of them is that all the current thread locals values (like the ``DISPATCHER.REQUEST``) are copied to the background thread that will actually execute the request, this happens [here](https://github.com/geoserver/geoserver/blob/b76bba7178d3505cd45e318e659c3b32faee4b5e/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/WPSExecutionManager.java#L350-L352), [here](https://github.com/geoserver/geoserver/blob/b76bba7178d3505cd45e318e659c3b32faee4b5e/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/WPSExecutionManager.java#L376-L393) and [here](https://github.com/geoserver/geoserver/blob/6e9e25c0c7cdda9ada9f33f8255130d3afc76801/src/main/src/main/java/org/geoserver/threadlocals/ThreadLocalsTransfer.java#L40-L45). The ``DISPATCHER.REQUEST`` is transferred by [this](https://github.com/geoserver/geoserver/blob/6e9e25c0c7cdda9ada9f33f8255130d3afc76801/src/main/src/main/java/org/geoserver/threadlocals/PublicThreadLocalTransfer.java#L18) thread local transfer.

The WPS process execution status response (which is the one having the problem) is written by the background thread [here](https://github.com/geoserver/geoserver/blob/b76bba7178d3505cd45e318e659c3b32faee4b5e/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/ExecuteResponseBuilder.java#L176-L177), the URL is produced by [this](https://github.com/geoserver/geoserver/blob/5424f5bf6384869a7e629d775230a4d4bb3cbb75/src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java#L19) URL mangler. The problem is that when the proxy base URL mangler, which being executed by the background thread, tries to access the original HTTP requests [here](https://github.com/geoserver/geoserver/blob/5424f5bf6384869a7e629d775230a4d4bb3cbb75/src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java#L163) it doesn't obtain the original headers.

The root problem is that although the ``DISPATCHER.REQUEST`` value was copied to the background thread the HTTP request object the dispatcher request references is owned by the container (Tomcat, Jetty, ...) and the contain will get ride of it once the main thread returns, so even if the background thread is accessing ``DISPATCHER.REQUEST`` it doesn't have access to right HTTP request.

Solution:
1. A thread local that holds the headers required by the proxy based URL mangler should be added [here](https://github.com/geoserver/geoserver/blob/5424f5bf6384869a7e629d775230a4d4bb3cbb75/src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java).
1. A dispatcher call back should take care of storing the necessary header values and clean them in the end of the request execution.
1. The thread local should be public so it is automatically handled by [this](https://github.com/geoserver/geoserver/blob/6e9e25c0c7cdda9ada9f33f8255130d3afc76801/src/main/src/main/java/org/geoserver/threadlocals/PublicThreadLocalTransfer.java) thread local transfer.
1. An integration tests needs to be implemented for this.

**Note from @aaime for you @tdipisa** , ALMAVIVA cluster doesn't have support for WPS asynchronous invocations (wps-jdbc plug-in is required).

**Comment by nmco** [comment] 2020-12-01 16:31
@taba90 let me know if my findings above make sense (and if my description is not too cryptic), if that's the case can you propose an estimate to implement the fix and test.

**Comment by simboss** [comment] 2020-12-01 17:33
@taba90 I am reassigning this to @aaime since we need an expedit fix and you have other priorities on your table.

**Comment by simboss** [comment] 2020-12-01 17:52
This is coming from GeoNode, hence it needs to be fixed on GeoServer 2.17 (GeoNode uses 2.17.2).

We might actually come up with a jar fix for the client for the time being then we upgrade to next 2.17 release.

**Comment by aaime** [comment] 2021-02-04 13:21
This has been solved for a while in GeoServer, was it tested? Can we close the issue?

**Comment by tdipisa** [comment] 2021-02-04 13:32
@aaime I've tested in on our MS dev and it is working.

**Closed** 2021-02-04 20:48 UTC
Labels: C183-ALMAVIVA-2020-GeoNode-DEV, Epic, MapStore, Priority: Blocker, geoserver, needs estimate
